name = "ai-chat-update-server"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
APP_NAME = "AI Chat Update Server"
APP_VERSION = "1.0.0"

[triggers]
crons = []

[build]
command = ""

[dev]
local = true
port = 8787

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
